name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - v2-k8s

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile
          file: ./Dockerfile.prod
          tags: |
            devsds/skupper-k8s-console:${{ github.sha }}
            devsds/skupper-k8s-console:latest
          push: true
